services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./cmd/web/public:/app/cmd/web/public
    command: -env=production -smtp-host=${host} -smtp-username=${username} -smtp-password=${password} --db-dsn="postgres://postgres:postgrespwd@db/sad_dev?sslmode=disable"
  db:
    image: arm64v8/postgres:16.3
    env_file:
      - ./.env/development/database
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
volumes:
  db_data:
